language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - pypy
  - pypy3

addons:
  apt:
    packages:
    - nodejs

install:
    - "pip install virtualenv"
    - "virtualenv ~/.venv"
    - "source ~/.venv/bin/activate"
    - "pip install tox"
    - "npm install && npm run-script lint"

script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27,pep8; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then tox -e py35,py3pep8; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then tox -e py36,py3pep8; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then tox -e pypy,pep8; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then tox -e pypy3,py3pep8; fi
